### ISSUE TITLE
Translation to Polish

### ISSUE THREAD

**Issue by blipinsk** [damien5314/TimeSinceTextView#3]
Hi,
I wanted to help you with a translation to Polish, but a simple division to plural and singular form might not be enough for some languages (including Polish).

Example (year):
-> 1 year ago == 1 rok temu
-> 2 years ago == 2 lata temu
-> 5 years ago == 5 lat temu

Have you considered using `plurals` instead of simple `strings`?

**Comment by damien5314** [comment]
Hi, thanks for pointing this out. I did not know about this feature in the SDK until now, but it sounds like it would solve the problem. I'll look into making the changes in English today or by the end of the week.

http://developer.android.com/guide/topics/resources/string-resource.html#Plurals

**Comment by damien5314** [comment]
This has been fixed in master, see the new [strings.xml](https://github.com/damien5314/TimeSinceTextView/blob/master/timesincetextview/src/main/res/values/strings.xml). Feel free to add your translation, and let me know if you have any more suggestions :+1: Thanks!
